apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicpod
spec:
  selector:
    matchLabels:
      type: webserver
  replicas: 3
  template:
    metadata:
      labels:
        type: webserver
    spec:
      containers:
      - name: webcont
        image: nginx
        ports:
        - containerPort: 80
